### ISSUE TITLE
Difference between having an empty trailer and None

### ISSUE THREAD

**Issue by peter-jerry-ye** [WebAssembly/wasi-http#131]
I have a possibly naive question since I'm not very familiar with HTTP.

Is there a necessity to define `option<trailers>` and `option<future<trailers>>`? What's the difference of having `some` empty trailers and having `none`?

**Comment by pavelsavara** [comment]
cc @dicej

**Comment by dicej** [comment]
I assume this question refers to https://github.com/WebAssembly/wasi-http/blob/f45069dcd486b2ece74f5623de4b72050cbce983/wit-0.3.0-draft/types.wit#L246-L271, correct?

We arrived at that API as part of the discussion in https://github.com/WebAssembly/wasi-http/pull/101.  IIRC, the idea was to use `<option<future<trailers>>` as a parameter to the `body` constructor so you could easily pass `none` rather than have to create a new `future` whose only purpose is to resolve to empty trailers, given that most applications probably won't use trailers at all.  I.e. it's an ergonomic and (slight) performance optimization, but in practice there should be no difference between passing `some` empty trailers and passing `none`.

I'm having trouble remembering why the `finish` function returns `option<trailers>` instead of `option<future<trailers>>`.  I _think_ the idea was that you'd only call `finish` after reading the body stream to the end, and the implementation would implicitly read any trailers as part of that process, storing them in a field and making them available immediately once `finish` is called.  That would imply that you could only read the trailers after explicitly draining the stream, and I don't remember if that was the intention or not.  @lukewagner do you happen remember?  I'm not finding an answer in the original discussion.

**Comment by peter-jerry-ye** [comment]
@dicej Thank you for you explanation. I was asking about the APIs for `outgoingbody`/`body` for both wit 0.2.0 and 0.3.0-draft.

> but in practice there should be no difference between passing some empty trailers and passing none.

That's what I'd like to confirm. Thank you.
