### ISSUE TITLE
Use a consistent future type

### ISSUE THREAD

**Issue by guybedford** [WebAssembly/wasi-http#76]
Currently `future-incoming-response` and `future-trailers` are both "futures", but have different shape of the future `get` definition (`option<result<result<T, E>>>` and `option<result<option<T>, E>>` respectively).

Would it be possible to converge on a single future pattern here?

**Comment by lukewagner** [comment]
(Sorry for the slow reply!)  I think the pattern we have fixed for pseudo-futures is that the return type of `get` is `option<result<X,Y>>` for some `X` and `Y`, but after that, the `X` and `Y` can be totally different for different pseudo-futures.  In this case, the reason for `future-incoming-response`'s inner `X` being a `result` is that we want to reflect a possible failure (which might throw when there is no `X`), whereas in the case of `future-trailers`, we want to reflect the fact that it's perfectly valid to have no/empty trailers.

**Comment by pchickey** [comment]
not quite - `get: func() -> option<result<V>>` is the method type for a future with output V, where the option is readiness, and the result is used to make sure the value V is consumed at most once. V may itself be a `result<X, Y>` where X is the success completion and Y is some failure, but that needs to be distinct from the failure when using the `get` function incorrectly.

the `future-trailers` function does not follow this pattern correctly: it does not have a way to error `get` is called multiple times after the future is ready. this burdens the implementation to maintain a copy of the value `result<option<trailers>, error>` so that it may be returned each time `get` is called. This is a mistake in the wit, but its not a big enough mistake to warrant correcting now that the RC has been cut, in my opinion.

**Comment by lukewagner** [comment]
Ah, gotcha; I saw they were both `option<result<...>>` but didn't look at the error payload type of `future-trailers.get`.  I could see this being a problem if we need a purely mechanical way to transform pseudo-futures into promises/futures, but if that's not happening, then agreed, it doesn't seem like a major problem.

**Comment by guybedford** [comment]
Resolved in https://github.com/WebAssembly/wasi-http/pull/86.
