### ISSUE TITLE
Are timeouts on request options specified in milliseconds or nanoseconds?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wasi-http#78]
[Currently](https://github.com/WebAssembly/wasi-http/blob/2befff608aa362aef20d79888b993787acd2f010/wit/types.wit#L321-L342) methods on `request-options` all end in `*-ms` which seems to imply that the argument has a unit of milliseconds. The type taken, however, is a `duration` which specifies that it's in nanoseconds. My guess is that this is an artifact of refactoring that was forgotten, but what's the intention here?

**Comment by lukewagner** [comment]
Yes, I think that was mistakenly introduced by a refactoring.  The original intention was indeed milliseconds, as suggested by the name.  This seems worth fixing in Preview 2, since otherwise it seems very likely to mislead folks.

Given the two obvious choices:
1. strip the `-ms`, inheriting the unit from `duration` (nanoseconds)
2. keep the `-ms`, change return type to `u64` or a new local type definition

I'd be inclined toward the former, but I think it's also a behavioral change (I'm guessing folks would've implemented milliseconds, given the name), as opposed to the latter which I expect is purely syntactic.

**Comment by pchickey** [comment]
Lets strip the `-ms`. I missed that when changing the types to duration.

If we are going to make a change to the RC, can we fix the future-trailers thing as well?

**Comment by elliottt** [comment]
I put up a draft pr for the fix to wasmtime's implementation: https://github.com/bytecodealliance/wasmtime/pull/7589

**Comment by elliottt** [comment]
Doh, @alexcrichton got to it first :)
